INSERT INTO advisor (name, email, password, status, phone_number) VALUES 
    ('Frederico Araújo Durão', 'fdurao@ufba.com', 'fad', 'ACTIVE', '71996136523'),
    ('Maycon Leone Maciel Peixoto', 'maycon.leone@ufba.com', 'mlmp', 'ACTIVE', NULL),
    ('Rita Suzana Pitangueira Maciel', 'rita.suzana@ufba.com', 'rspm', 'ACTIVE', NULL),
    ('Christina Von Flach Garcia Chavez', 'flach@ufba.com', 'cvfgc', 'ACTIVE', NULL),
    ('Raimundo José de Araújo Macêdo', 'macedo@ufba.com', 'rjdam', 'ACTIVE', NULL),
    ('Gecynalda Soares da Silva Gomes', 'gecynaldassg@ufba.com', 'gsdsg', 'ACTIVE', NULL),
    ('Gustavo Bittencourt Figueiredo', 'gustavobf@ufba.com', 'gbf', 'ACTIVE', NULL),
    ('Danilo Barbosa Coimbra', 'coimbra.danilo@ufba.com', 'dbc', 'ACTIVE', NULL),
    ('Ivan do Carmo Machado', 'ivan.machado@ufba.com', 'idcm', 'ACTIVE', NULL),
    ('Leobino Nascimento Sampaio', 'leobino@ufba.com', 'lns', 'ACTIVE', NULL),
    ('Luciano Rebouças de Oliveira', 'lrebouca@ufba.com', 'lrdo', 'ACTIVE', NULL),
    ('Ecivaldo de Souza Matos', 'ecivaldo@ufba.com', 'edsm', 'ACTIVE', NULL),
    ('Vaninha Vieira', 'vaninha@ufba.com', 'vv', 'ACTIVE', NULL),
    ('Manoel Gomes de Mendonça Neto', 'manoel.mendonca@ufba.com', 'mgdmn', 'ACTIVE', NULL),
    ('Rafael Augusto de Melo', 'rafael.melo@ufba.com', 'radm', 'ACTIVE', NULL),
    ('Cassio Vinícius Serafim Prazeres', 'prazeres@ufba.com', 'cvsp', 'ACTIVE', NULL),
    ('Laís do Nascimento Salvador', 'laisns@ufba.com', 'ldns', 'ACTIVE', NULL),
    ('Eduardo Santana de Almeida', 'eduardo.almeida@ufba.com', 'esda', 'ACTIVE', NULL),
    ('George Marconi de Araújo Lima', 'gmlima@ufba.com', 'gmdal', 'ACTIVE', NULL),
    ('Marcos Ennes Barreto', 'marcosb@ufba.com', 'meb', 'INACTIVE', NULL),
    ('Maurício Pamplona Segundo', 'mauriciops@ufba.com', 'mps', 'INACTIVE', NULL),
    ('Aline Maria Santos Andrade', 'aline@ufba.com', 'amsa', 'ACTIVE', NULL),
    ('Antônio Lopes Apolinário Júnior', 'antonio.apolinario@ufba.com', 'alaj', 'ACTIVE', NULL),
    ('Cláudio Nogueira Sant''Anna', 'claudionsa@ufba.com', 'cns', 'ACTIVE', NULL),
    ('Daniela Barreiro Claro', 'dclaro@ufba.com', 'dbc', 'ACTIVE', NULL),
    ('Rodrigo Rocha Gomes e Souza', 'rodrigorgs@ufba.com', 'rrges', 'ACTIVE', NULL),
    ('Tiago de Oliveira Januário', 'januario@ufba.com', 'tdoj', 'INACTIVE', NULL),
    ('Tatiane Nogueira Rios', 'tatiane.nogueira@ufba.com', 'tnr', 'ACTIVE', NULL),
    ('Ricardo Araújo Rios', 'ricardoar@ufba.com', 'rar', 'ACTIVE', NULL),
    ('Vinicius Tavares Petrucci', 'vpetrucci@ufba.com', 'vtp', 'ACTIVE', NULL),
    ('Marlo Vieira dos Santos e Souza', 'msouza1@ufba.com', 'mvdses', 'ACTIVE', NULL),
    ('Fabíola Gonçalves Pereira Greve', 'fabiola@ufba.com', 'fgpg', 'INACTIVE', NULL);